language: python
python: 3.6
install:
  - "pip install -U pip"
  - "pip install 'Lektor>=3'"
script: "lektor build"

deploy:
  - provider: script
    script: "lektor deploy develop"
    on:
       branch: develop
  - provider: script
    script: "lektor deploy production"
    on:
       branch: production

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d23c08216a7b3f1a005
